[package]
name = "atmogrid"
version = "0.1.0"
description = "AtmoGrid — gamified DePIN air-quality oracle"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]
name = "atmogrid"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
